### PR TITLE
[#88] More version specific Internal Metrics

### PR DESCRIPTION
**Pull request by resyfer**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
I'll look once the conflict is fixed, and pull request is rebased

**Comment by resyfer** [comment]
@jesperpedersen I was keeping this PR for copying some examples from the various `postgresql-*.yaml` into `INTERNAL_YAML`.

I will look do some searching into what is preferred by people as necessary metrics out of the examples I've provided and then add those into `INTERNAL_YAML`.

Do you have any preference on the newly added metrics?

**Comment by jesperpedersen** [comment]
I think this would be like the PostgreSQL 16 file , and pgexporter would use the correct part for each server

**Comment by resyfer** [comment]
> I think this would be like the PostgreSQL 16 file , and pgexporter would use the correct part for each server

Yeah I'll take the metrics from there, but I don't think all of them should be taken? The output file does become quite big, and even though I don't think anyone will view the metrics output directly, I do have an inclination towards keeping it to as much as needed.

**Comment by jesperpedersen** [comment]
Clear the draft status once you think it is ready

**Comment by resyfer** [comment]
I've rectified my...very silly mistake....I didn't add the `\n` at the end of each string, forgetting that the strings will get concatenated one after the other 🥲 and I was wondering why it doesn't recognize the YAML syntax.

**Comment by jesperpedersen** [comment]
Please, rebase

**Comment by resyfer** [comment]
@jesperpedersen PTAL...by mistake I had rebased it with the grafana branch, but I removed the changes later which is why the deletion of files are shown.

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
