### PR TITLE
[#76] PostgreSQL V11 metrics examples

### PR DESCRIPTION
**Pull request by resyfer**

### CODE REVIEW

**Comment by resyfer** [comment]
@jesperpedersen PTAL

**Comment by jesperpedersen** [comment]
`postgresql-11.yml` == `postgresql-10.yml` + all queries specific to 11

**Comment by jesperpedersen** [comment]
Can you rebase ?

**Comment by resyfer** [comment]
@jesperpedersen

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
