### PR TITLE
[#74] PostgreSQL V10 metrics examples

### PR DESCRIPTION
**Pull request by resyfer**

### CODE REVIEW

**Comment by resyfer** [comment]
@jesperpedersen PTAL

**Comment by jesperpedersen** [comment]
Rebase, please

**Comment by jesperpedersen** [comment]
This file should be locked to `version: 10`

**Comment by resyfer** [comment]
> Rebase, please

Done

> This file should be locked to `version: 10`

Yeah the topmost `version: 10` ensures that the default version is kept at `10`, and there are no queries in `postgresql-10.yaml` with versions other than `10`.

**Comment by resyfer** [comment]
@jesperpedersen PTAL. I've made the changes according to what I think you wanted to all the version yaml PRs. If I'm mistaken, I'll fix it quickly.

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
