### PR TITLE
 Installation instructions for Red Hat RPM based distributions

### PR DESCRIPTION
**Pull request by nikitabugrovsky**
Issue: pgexporter/pgexporter#21

### CODE REVIEW

**Comment by jesperpedersen** [comment]
You need to add yourself to the `AUTHORS` file as well

**Comment by jesperpedersen** [comment]
There is no reason to have the same command twice...

**Comment by nikitabugrovsky** [comment]
@jesperpedersen with e45ab3b to 2a3fe6e I changed commit message as well.

**Comment by jesperpedersen** [comment]
You need to remove the "Fedora" part still... do

```
[#21] Installation instructions for Red Hat RPM based distributions
```

as the commit message - you don't need to list the files changed.

**Comment by nikitabugrovsky** [comment]
@jesperpedersen there is one difference in package naming between Fedora & RHEL based: `liblz4`, `liblz4-dev` vs `lz4`,` lz4-devel` respectively. Do you think it would be better to stick to 2 different lines?

**Comment by jesperpedersen** [comment]
Ah, those are typos -- `pgexporter` doesn't depend on LZ4

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
